name: Validate PR
on:
  pull_request:
jobs:
  backend_unit_tests:
    name: Backend unit tests
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Podman
        run: brew install podman
      - name: Setup Podman
        run: |
          podman machine init
          podman machine start
      - name: Run Postgres
        run: podman run -p 5432:5432 --name some-postgres -e POSTGRES_PASSWORD=postgres -d postgres:14
      - name: Setup Golang 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run unit tests
        run: |
          cd backend
          go test -v ./...